import type { AutomationSystem } from '../schemas/libraries';

export const AUTOMATION_SEEDS: AutomationSystem[] = [
  {
    system_id: 'autostore_grid',
    name: 'AutoStore Grid',
    category: 'g2p_cubic',
    supplier_refs: ['AutoStore'],
    typicalDensity: { unit: 'bins/m2', value: 9 }, // × stack_height × 0.85
    throughputPerRobotPerHour: 500,
    defaultPackingEfficiency: 0.82,
    notes: 'Density = 9 × stack_height × 0.85. Grid-based, high port throughput.',
  },
  {
    system_id: 'exotec_skypod',
    name: 'Exotec Skypod',
    category: 'g2p_shelf',
    supplier_refs: ['Exotec'],
    typicalDensity: { unit: 'compartments/m2', value: 150 },
    throughputPerRobotPerHour: 25,
    defaultPackingEfficiency: 0.75,
  },
  {
    system_id: 'geekplus_p_series',
    name: 'Geek+ P-Series (G2P shelf)',
    category: 'g2p_shelf',
    supplier_refs: ['Geek+'],
    typicalDensity: { unit: 'compartments/m2', value: 140 },
    throughputPerRobotPerHour: 20,
    defaultPackingEfficiency: 0.75,
    notes: 'Dominant ASEAN/China G2P solution; Chinese vendor first-class.',
  },
  {
    system_id: 'hai_haipick_acr',
    name: 'HAI Robotics HaiPick ACR',
    category: 'acr_case',
    supplier_refs: ['HAI Robotics'],
    typicalDensity: { unit: 'cases/m2', value: 180 },
    throughputPerRobotPerHour: 300,
    defaultPackingEfficiency: 0.80,
    notes: 'Autonomous Case-handling Robot; Chinese vendor first-class.',
  },
  {
    system_id: 'quicktron_multi_tier',
    name: 'Quicktron Multi-Tier',
    category: 'case_picking',
    supplier_refs: ['Quicktron'],
    typicalDensity: { unit: 'cases/m2', value: 120 },
    throughputPerRobotPerHour: 250,
    defaultPackingEfficiency: 0.78,
    notes: 'Chinese vendor first-class.',
  },
  {
    system_id: 'pallet_shuttle_single',
    name: 'Pallet Shuttle (single-deep)',
    category: 'pallet_shuttle',
    supplier_refs: ['Mecalux', 'HAI Radio Shuttle', 'AR Racking'],
    typicalDensity: { unit: 'pallets/m2', value: 20 },
    throughputPerAislePerHour: 50,
    defaultPackingEfficiency: 0.90,
  },
  {
    system_id: 'pallet_shuttle_mother_child',
    name: 'Pallet Shuttle (mother-child)',
    category: 'pallet_shuttle',
    supplier_refs: ['Mecalux', 'HAI Radio Shuttle'],
    typicalDensity: { unit: 'pallets/m2', value: 38 },
    throughputPerAislePerHour: 40,
    defaultPackingEfficiency: 0.90,
  },
  {
    system_id: 'mini_load_asrs',
    name: 'Mini-Load ASRS (crane)',
    category: 'mini_load_asrs',
    supplier_refs: ['Dematic', 'SSI Schaefer', 'Vanderlande'],
    typicalDensity: { unit: 'totes/m2', value: 70 },
    throughputPerAislePerHour: 100,
    defaultPackingEfficiency: 0.85,
  },
  {
    system_id: 'pallet_agv_kiva',
    name: 'Pallet AGV (Kiva-class)',
    category: 'pallet_agv',
    supplier_refs: ['Quicktron', 'Geek+ M-Series'],
    typicalDensity: { unit: 'trips/hr/agv', value: 40 },
    defaultPackingEfficiency: 0.80,
  },
  {
    system_id: 'libiao_cross_belt_sorter',
    name: 'Libiao Cross-Belt Sorter',
    category: 'sortation',
    supplier_refs: ['Libiao Robotics'],
    typicalDensity: { unit: 'parcels/hr', value: 15000 },
    throughputPerHour: 15000,
    defaultPackingEfficiency: 1.0,
    notes: 'Chinese vendor first-class; parcel sortation.',
  },
];
