import type { MheClass } from '../schemas/libraries';

export const MHE_SEEDS: MheClass[] = [
  {
    mhe_id: 'walkie_pallet',
    name: 'Walkie Pallet Truck',
    category: 'walkie',
    aisleWidthMmMin: 2000, aisleWidthMmDefault: 2200, aisleTransferWidthMm: 0, endOfAisleTurnaroundMm: 2500,
    liftHeightMmMax: 200, travelSpeedKph: 5, liftSpeedMpm: 5,
    battery: { type: 'lithium_opportunity', chargingFootprintM2PerUnit: 1, swapStationM2: 0, chargingKva: 2 },
    utilisationTargetDefault: 0.55, usefulLifeYears: 6,
  },
  {
    mhe_id: 'counterbalance_2_5t_4w',
    name: 'Counterbalance 2.5t (4-wheel)',
    category: 'counterbalance',
    aisleWidthMmMin: 3500, aisleWidthMmDefault: 3800, aisleTransferWidthMm: 0, endOfAisleTurnaroundMm: 4500,
    liftHeightMmMax: 6000, travelSpeedKph: 18, liftSpeedMpm: 30,
    battery: { type: 'lithium_opportunity', chargingFootprintM2PerUnit: 3, swapStationM2: 0, chargingKva: 8 },
    utilisationTargetDefault: 0.65, usefulLifeYears: 8,
  },
  {
    mhe_id: 'counterbalance_2_5t_3w',
    name: 'Counterbalance 2.5t (3-wheel, tight ASEAN)',
    category: 'counterbalance',
    aisleWidthMmMin: 3200, aisleWidthMmDefault: 3400, aisleTransferWidthMm: 0, endOfAisleTurnaroundMm: 4000,
    liftHeightMmMax: 5500, travelSpeedKph: 16, liftSpeedMpm: 28,
    battery: { type: 'lithium_opportunity', chargingFootprintM2PerUnit: 2.5, swapStationM2: 0, chargingKva: 8 },
    utilisationTargetDefault: 0.65, usefulLifeYears: 8,
    notes: 'Tight-turning 3-wheel favoured in ASEAN compact DCs.',
  },
  {
    mhe_id: 'stand_on_stacker',
    name: 'Stand-On Stacker',
    category: 'stacker',
    aisleWidthMmMin: 2400, aisleWidthMmDefault: 2600, aisleTransferWidthMm: 0, endOfAisleTurnaroundMm: 2800,
    liftHeightMmMax: 5500, travelSpeedKph: 10, liftSpeedMpm: 22,
    battery: { type: 'lithium_opportunity', chargingFootprintM2PerUnit: 2, swapStationM2: 0, chargingKva: 5 },
    utilisationTargetDefault: 0.6, usefulLifeYears: 7,
    notes: 'Common Japan/Korea convenience DCs.',
  },
  {
    mhe_id: 'reach_truck_single',
    name: 'Reach Truck (single-deep)',
    category: 'reach',
    aisleWidthMmMin: 2800, aisleWidthMmDefault: 3000, aisleTransferWidthMm: 0, endOfAisleTurnaroundMm: 3500,
    liftHeightMmMax: 11000, travelSpeedKph: 12, liftSpeedMpm: 40,
    battery: { type: 'lithium_opportunity', chargingFootprintM2PerUnit: 3, swapStationM2: 0, chargingKva: 10 },
    utilisationTargetDefault: 0.72, usefulLifeYears: 8,
  },
  {
    mhe_id: 'reach_truck_double',
    name: 'Reach Truck (double-deep)',
    category: 'reach',
    aisleWidthMmMin: 2900, aisleWidthMmDefault: 3100, aisleTransferWidthMm: 0, endOfAisleTurnaroundMm: 3700,
    liftHeightMmMax: 11000, travelSpeedKph: 12, liftSpeedMpm: 40,
    battery: { type: 'lithium_opportunity', chargingFootprintM2PerUnit: 3, swapStationM2: 0, chargingKva: 10 },
    utilisationTargetDefault: 0.70, usefulLifeYears: 8,
  },
  {
    mhe_id: 'vna_turret',
    name: 'VNA Turret Truck',
    category: 'very_narrow_aisle',
    aisleWidthMmMin: 1650, aisleWidthMmDefault: 1800, aisleTransferWidthMm: 6000, endOfAisleTurnaroundMm: 3500,
    liftHeightMmMax: 14000, travelSpeedKph: 10, liftSpeedMpm: 30,
    ratePerTaskPerHour: { putawayPallet: 28, replenPallet: 24, retrievePallet: 28 },
    battery: { type: 'lithium_opportunity', chargingFootprintM2PerUnit: 2, swapStationM2: 0, chargingKva: 5 },
    utilisationTargetDefault: 0.70, usefulLifeYears: 8,
    operatorCertification: 'VNA_endorsement_required',
    notes: 'Flat floor FM2 min. Wire-guided or rail-guided.',
  },
  {
    mhe_id: 'man_up_order_picker',
    name: 'Man-Up Order Picker (high-level)',
    category: 'order_picker',
    aisleWidthMmMin: 1400, aisleWidthMmDefault: 1600, aisleTransferWidthMm: 4000, endOfAisleTurnaroundMm: 2800,
    liftHeightMmMax: 12000, travelSpeedKph: 10, liftSpeedMpm: 25,
    battery: { type: 'lithium_opportunity', chargingFootprintM2PerUnit: 2, swapStationM2: 0, chargingKva: 5 },
    utilisationTargetDefault: 0.65, usefulLifeYears: 7,
    operatorCertification: 'harness_and_training',
  },
  {
    mhe_id: 'medium_level_order_picker',
    name: 'Medium-Level Order Picker (3–6 m)',
    category: 'order_picker',
    aisleWidthMmMin: 1300, aisleWidthMmDefault: 1500, aisleTransferWidthMm: 3000, endOfAisleTurnaroundMm: 2500,
    liftHeightMmMax: 6000, travelSpeedKph: 10, liftSpeedMpm: 18,
    battery: { type: 'lithium_opportunity', chargingFootprintM2PerUnit: 2, swapStationM2: 0, chargingKva: 4 },
    utilisationTargetDefault: 0.68, usefulLifeYears: 7,
    notes: 'Multi-tier mezzanine picking.',
  },
  {
    mhe_id: 'llop',
    name: 'LLOP (Low-Level Order Picker)',
    category: 'order_picker',
    aisleWidthMmMin: 2000, aisleWidthMmDefault: 2200, aisleTransferWidthMm: 0, endOfAisleTurnaroundMm: 2400,
    liftHeightMmMax: 300, travelSpeedKph: 12, liftSpeedMpm: 0,
    battery: { type: 'lithium_opportunity', chargingFootprintM2PerUnit: 1.5, swapStationM2: 0, chargingKva: 3 },
    utilisationTargetDefault: 0.70, usefulLifeYears: 7,
  },
  {
    mhe_id: 'tugger_train',
    name: 'Tugger / Train',
    category: 'tugger',
    aisleWidthMmMin: 2400, aisleWidthMmDefault: 2800, aisleTransferWidthMm: 0, endOfAisleTurnaroundMm: 3500,
    liftHeightMmMax: 0, travelSpeedKph: 12, liftSpeedMpm: 0,
    battery: { type: 'lithium_opportunity', chargingFootprintM2PerUnit: 2, swapStationM2: 0, chargingKva: 4 },
    utilisationTargetDefault: 0.70, usefulLifeYears: 8,
  },
  {
    mhe_id: 'amr_locus',
    name: 'AMR (Locus/Fetch/Geek+ P-series)',
    category: 'amr_agv',
    aisleWidthMmMin: 1200, aisleWidthMmDefault: 1500, aisleTransferWidthMm: 0, endOfAisleTurnaroundMm: 2000,
    liftHeightMmMax: 0, travelSpeedKph: 6, liftSpeedMpm: 0,
    battery: { type: 'lithium_opportunity', chargingFootprintM2PerUnit: 1, swapStationM2: 0, chargingKva: 2 },
    utilisationTargetDefault: 0.85, usefulLifeYears: 6,
    notes: 'Collaborates with human pickers. Fleet-dependent throughput with interference curve.',
  },
  {
    mhe_id: 'agv_pallet',
    name: 'AGV Pallet (Quicktron/Geek+ M-series Kiva-class)',
    category: 'amr_agv',
    aisleWidthMmMin: 2200, aisleWidthMmDefault: 2500, aisleTransferWidthMm: 0, endOfAisleTurnaroundMm: 3000,
    liftHeightMmMax: 1500, travelSpeedKph: 5, liftSpeedMpm: 10,
    battery: { type: 'lithium_opportunity', chargingFootprintM2PerUnit: 1.2, swapStationM2: 0, chargingKva: 3 },
    utilisationTargetDefault: 0.80, usefulLifeYears: 7,
    notes: 'Point-to-point pallet moves; Chinese vendors dominant in ASEAN.',
  },
];
