import type { RackSystem } from '../schemas/libraries';

const selectiveBase = {
  category: 'pallet_racking',
  bay: { widthMm: 2400, depthMm: 1100, heightMmDefault: 9000, heightMmRange: [3000, 12000] as [number, number] },
  slotsPerBay: 2,
  levelsDefault: 5,
  load: { perLevelKg: 2000, maxLoadPerBeamPairKg: 3000, maxSinglePalletKg: 1500 },
  aisle: { widthMmMin: 2800, widthMmDefault: 3000, crossAisleMm: 3500 },
  flueSpace: { transverseMm: 150, longitudinalMm: 300 },
  bottomBeamClearanceMm: 150,
  beamThicknessMm: 100,
  minPresentationPallets: 2,
  honeycombing: { verticalFactor: 0.92, horizontalDefault: 0.88 },
  fillFactor: 0.95,
  slotVolumeM3: 1.32,
  storageType: 'selective',
  densityRating: 'low' as const,
  seismic: { designCategory: 'C', soilClassRating: 'B', importanceLevel: 2, anchorageRequired: true, bracingPattern: '2-bay' },
  structuralBayBlock: 3,
  rackMassKgPerPosition: 45,
};

export const RACK_SEEDS: RackSystem[] = [
  {
    system_id: 'selective_single_deep_t11',
    name: 'Single-Deep Selective (T11)',
    supplier_refs: ['SSI Schaefer PR600', 'Dematic', 'Colby', 'Stow', 'Nanjing Inform', 'HAI Racking'],
    slotTypeCompat: ['PFP'],
    notes: 'Baseline. 100% selectivity. Fits T11 2-pallet-wide.',
    ...selectiveBase,
    costPerPalletPositionUsd: 80,
  },
  {
    system_id: 'selective_single_deep_1200x1000',
    name: 'Single-Deep Selective (1200×1000)',
    supplier_refs: ['SSI Schaefer', 'Nanjing Inform', 'HAI Racking'],
    slotTypeCompat: ['PFP'],
    ...selectiveBase,
    bay: { widthMm: 2700, depthMm: 1100, heightMmDefault: 9000, heightMmRange: [3000, 12000] },
    costPerPalletPositionUsd: 80,
  },
  {
    system_id: 'selective_double_deep',
    name: 'Double-Deep Selective',
    supplier_refs: ['SSI Schaefer', 'Dematic'],
    slotTypeCompat: ['PFP'],
    ...selectiveBase,
    densityRating: 'medium',
    storageType: 'double_deep',
    honeycombing: { verticalFactor: 0.92, horizontalDefault: 0.82 },
    costPerPalletPositionUsd: 90,
    notes: '~2x density vs single-deep; requires deep-reach truck.',
  },
  {
    system_id: 'pushback_3_deep',
    name: 'Push-Back 3-Deep',
    supplier_refs: ['UNARCO', 'Mecalux', 'SSI Schaefer'],
    slotTypeCompat: ['PFP'],
    ...selectiveBase,
    densityRating: 'medium',
    storageType: 'push_back',
    honeycombing: { verticalFactor: 0.88, horizontalDefault: 0.75 },
    costPerPalletPositionUsd: 140,
  },
  {
    system_id: 'pushback_5_deep',
    name: 'Push-Back 5-Deep',
    supplier_refs: ['UNARCO', 'Mecalux'],
    slotTypeCompat: ['PFP'],
    ...selectiveBase,
    densityRating: 'high',
    storageType: 'push_back',
    honeycombing: { verticalFactor: 0.88, horizontalDefault: 0.70 },
    costPerPalletPositionUsd: 170,
  },
  {
    system_id: 'drive_in_4_deep',
    name: 'Drive-In 4-Deep (LIFO)',
    supplier_refs: ['SSI Schaefer', 'Colby', 'Nanjing Inform'],
    slotTypeCompat: ['PFP'],
    ...selectiveBase,
    densityRating: 'high',
    storageType: 'drive_in',
    honeycombing: { verticalFactor: 0.90, horizontalDefault: 0.65 },
    costPerPalletPositionUsd: 110,
  },
  {
    system_id: 'drive_in_8_deep',
    name: 'Drive-In 8-Deep (LIFO)',
    supplier_refs: ['SSI Schaefer', 'Nanjing Inform'],
    slotTypeCompat: ['PFP'],
    ...selectiveBase,
    densityRating: 'very_high',
    storageType: 'drive_in',
    honeycombing: { verticalFactor: 0.90, horizontalDefault: 0.55 },
    costPerPalletPositionUsd: 130,
  },
  {
    system_id: 'drive_through',
    name: 'Drive-Through (FIFO, ASEAN)',
    supplier_refs: ['Dematic', 'HAI Racking'],
    slotTypeCompat: ['PFP'],
    ...selectiveBase,
    densityRating: 'high',
    storageType: 'drive_through',
    honeycombing: { verticalFactor: 0.90, horizontalDefault: 0.60 },
    costPerPalletPositionUsd: 135,
    notes: 'Common ASEAN FIFO for ambient FMCG.',
  },
  {
    system_id: 'pallet_flow_gravity',
    name: 'Pallet Flow Gravity (FIFO)',
    supplier_refs: ['Interlake Mecalux', 'UNEX', 'SSI Schaefer'],
    slotTypeCompat: ['PFP'],
    ...selectiveBase,
    densityRating: 'very_high',
    storageType: 'pallet_flow',
    honeycombing: { verticalFactor: 0.88, horizontalDefault: 0.60 },
    costPerPalletPositionUsd: 220,
  },
  {
    system_id: 'vna_selective_1650',
    name: 'VNA Selective (1650 mm aisle)',
    supplier_refs: ['Dematic', 'SSI Schaefer'],
    slotTypeCompat: ['PFP'],
    ...selectiveBase,
    bay: { widthMm: 2400, depthMm: 1100, heightMmDefault: 12000, heightMmRange: [8000, 14000] },
    levelsDefault: 7,
    aisle: { widthMmMin: 1650, widthMmDefault: 1650, crossAisleMm: 3500 },
    densityRating: 'high',
    costPerPalletPositionUsd: 120,
    notes: 'Requires VNA truck + FM2 floor + wire/rail guidance.',
  },
  {
    system_id: 'vna_selective_1800',
    name: 'VNA Selective (1800 mm aisle)',
    supplier_refs: ['Dematic', 'SSI Schaefer'],
    slotTypeCompat: ['PFP'],
    ...selectiveBase,
    bay: { widthMm: 2400, depthMm: 1100, heightMmDefault: 12000, heightMmRange: [8000, 14000] },
    levelsDefault: 7,
    aisle: { widthMmMin: 1800, widthMmDefault: 1800, crossAisleMm: 3500 },
    densityRating: 'high',
    costPerPalletPositionUsd: 115,
  },
  {
    system_id: 'cls_schaefer_sk2',
    name: 'Carton Live Storage — Schaefer SK2',
    category: 'carton_live',
    supplier_refs: ['SSI Schaefer'],
    bay: { widthMm: 2500, depthMm: 2000, heightMmDefault: 2500, heightMmRange: [2000, 3500] },
    slotsPerBay: 10,
    levelsDefault: 4,
    load: { perLevelKg: 250, maxLoadPerBeamPairKg: 500, maxSinglePalletKg: 0 },
    aisle: { widthMmMin: 2400, widthMmDefault: 2400, crossAisleMm: 3000 },
    flueSpace: { transverseMm: 50, longitudinalMm: 100 },
    bottomBeamClearanceMm: 100,
    beamThicknessMm: 50,
    minPresentationPallets: 0,
    honeycombing: { verticalFactor: 0.95, horizontalDefault: 0.90 },
    fillFactor: 0.90,
    slotVolumeM3: 0.18,
    slotTypeCompat: ['CLS'],
    storageType: 'carton_live',
    densityRating: 'high',
    seismic: { designCategory: 'C', soilClassRating: 'B', importanceLevel: 2, anchorageRequired: true, bracingPattern: '2-bay' },
    structuralBayBlock: 2,
    rackMassKgPerPosition: 8,
    variants: [
      { id: 'sk2_depth_2000', depthMm: 2000, casesPerLane: 8 },
      { id: 'sk3_depth_3000', depthMm: 3000, casesPerLane: 12 },
      { id: 'sk4_depth_4000', depthMm: 4000, casesPerLane: 16 },
    ],
    costPerPalletPositionUsd: 180,
  },
  {
    system_id: 'longspan_shelving',
    name: 'Longspan Shelving',
    category: 'shelving',
    supplier_refs: ['SSI Schaefer', 'Dexion', 'Elite Storage'],
    bay: { widthMm: 2000, depthMm: 600, heightMmDefault: 2500, heightMmRange: [2000, 4500] },
    slotsPerBay: 4,
    levelsDefault: 5,
    load: { perLevelKg: 300, maxLoadPerBeamPairKg: 600, maxSinglePalletKg: 0 },
    aisle: { widthMmMin: 1200, widthMmDefault: 1500, crossAisleMm: 2400 },
    flueSpace: { transverseMm: 50, longitudinalMm: 50 },
    bottomBeamClearanceMm: 100,
    beamThicknessMm: 50,
    minPresentationPallets: 0,
    honeycombing: { verticalFactor: 0.95, horizontalDefault: 0.95 },
    fillFactor: 0.90,
    slotVolumeM3: 0.3,
    slotTypeCompat: ['Shelf'],
    storageType: 'shelving',
    densityRating: 'medium',
    seismic: { designCategory: 'C', soilClassRating: 'B', importanceLevel: 2, anchorageRequired: true, bracingPattern: 'cross' },
    structuralBayBlock: 1,
    rackMassKgPerPosition: 4,
    costPerPalletPositionUsd: 25,
  },
  {
    system_id: 'bin_shelving',
    name: 'Bin Shelving (small parts)',
    category: 'shelving',
    supplier_refs: ['Akro-Mils', 'SSI Schaefer'],
    bay: { widthMm: 900, depthMm: 400, heightMmDefault: 2200, heightMmRange: [1800, 2500] },
    slotsPerBay: 20,
    levelsDefault: 5,
    load: { perLevelKg: 100, maxLoadPerBeamPairKg: 200, maxSinglePalletKg: 0 },
    aisle: { widthMmMin: 900, widthMmDefault: 1200, crossAisleMm: 1800 },
    flueSpace: { transverseMm: 25, longitudinalMm: 25 },
    bottomBeamClearanceMm: 50,
    beamThicknessMm: 25,
    minPresentationPallets: 0,
    honeycombing: { verticalFactor: 0.98, horizontalDefault: 0.95 },
    fillFactor: 0.85,
    slotVolumeM3: 0.036,
    slotTypeCompat: ['Shelf'],
    storageType: 'bin_shelving',
    densityRating: 'high',
    seismic: { designCategory: 'C', soilClassRating: 'B', importanceLevel: 2, anchorageRequired: true, bracingPattern: 'cross' },
    structuralBayBlock: 1,
    rackMassKgPerPosition: 1.5,
    costPerPalletPositionUsd: 10,
  },
  {
    system_id: 'mobile_shelving',
    name: 'Mobile Shelving (high-density)',
    category: 'shelving',
    supplier_refs: ['Montel', 'Spacesaver', 'SSI Schaefer'],
    bay: { widthMm: 1500, depthMm: 600, heightMmDefault: 2500, heightMmRange: [2000, 3000] },
    slotsPerBay: 15,
    levelsDefault: 5,
    load: { perLevelKg: 200, maxLoadPerBeamPairKg: 400, maxSinglePalletKg: 0 },
    aisle: { widthMmMin: 1000, widthMmDefault: 1200, crossAisleMm: 2000 },
    flueSpace: { transverseMm: 25, longitudinalMm: 25 },
    bottomBeamClearanceMm: 100,
    beamThicknessMm: 30,
    minPresentationPallets: 0,
    honeycombing: { verticalFactor: 0.95, horizontalDefault: 0.92 },
    fillFactor: 0.85,
    slotVolumeM3: 0.045,
    slotTypeCompat: ['Shelf'],
    storageType: 'mobile',
    densityRating: 'very_high',
    seismic: { designCategory: 'C', soilClassRating: 'B', importanceLevel: 2, anchorageRequired: true, bracingPattern: 'rail' },
    structuralBayBlock: 1,
    rackMassKgPerPosition: 3,
    costPerPalletPositionUsd: 80,
    notes: 'Single-access aisle; best for low-velocity/archive.',
  },
  {
    system_id: 'multi_tier_mezzanine',
    name: 'Multi-Tier Mezzanine Shelving (3-tier ASEAN)',
    category: 'mezzanine_shelving',
    supplier_refs: ['SSI Schaefer', 'Stow', 'HAI Racking'],
    bay: { widthMm: 2000, depthMm: 600, heightMmDefault: 7500, heightMmRange: [6000, 10000] },
    slotsPerBay: 12,
    levelsDefault: 3,
    load: { perLevelKg: 250, maxLoadPerBeamPairKg: 500, maxSinglePalletKg: 0 },
    aisle: { widthMmMin: 1200, widthMmDefault: 1500, crossAisleMm: 2400 },
    flueSpace: { transverseMm: 50, longitudinalMm: 50 },
    bottomBeamClearanceMm: 100,
    beamThicknessMm: 50,
    minPresentationPallets: 0,
    honeycombing: { verticalFactor: 0.90, horizontalDefault: 0.88 },
    fillFactor: 0.85,
    slotVolumeM3: 0.36,
    slotTypeCompat: ['Shelf'],
    storageType: 'multi_tier',
    densityRating: 'very_high',
    seismic: { designCategory: 'C', soilClassRating: 'B', importanceLevel: 2, anchorageRequired: true, bracingPattern: '2-bay' },
    structuralBayBlock: 2,
    rackMassKgPerPosition: 12,
    costPerPalletPositionUsd: 60,
    notes: 'Common SG/HK/KR. Requires goods lift + fire compartmentation per tier.',
  },
  {
    system_id: 'cantilever',
    name: 'Cantilever (long goods)',
    category: 'cantilever',
    supplier_refs: ['SSI Schaefer', 'Stow'],
    bay: { widthMm: 1500, depthMm: 1200, heightMmDefault: 5000, heightMmRange: [3000, 7000] },
    slotsPerBay: 1,
    levelsDefault: 4,
    load: { perLevelKg: 1000, maxLoadPerBeamPairKg: 2000, maxSinglePalletKg: 500 },
    aisle: { widthMmMin: 3000, widthMmDefault: 3500, crossAisleMm: 4000 },
    flueSpace: { transverseMm: 100, longitudinalMm: 200 },
    bottomBeamClearanceMm: 150,
    beamThicknessMm: 80,
    minPresentationPallets: 0,
    honeycombing: { verticalFactor: 0.85, horizontalDefault: 0.80 },
    fillFactor: 0.80,
    slotVolumeM3: 2.5,
    slotTypeCompat: ['PFP', 'Shelf'],
    storageType: 'cantilever',
    densityRating: 'medium',
    seismic: { designCategory: 'C', soilClassRating: 'B', importanceLevel: 2, anchorageRequired: true, bracingPattern: 'cross' },
    structuralBayBlock: 2,
    rackMassKgPerPosition: 70,
    costPerPalletPositionUsd: 95,
    notes: 'Furniture, piping, timber.',
  },
  {
    system_id: 'tyre_rack',
    name: 'Tyre Rack (auto parts)',
    category: 'tyre',
    supplier_refs: ['SSI Schaefer'],
    bay: { widthMm: 2000, depthMm: 800, heightMmDefault: 4000, heightMmRange: [3000, 6000] },
    slotsPerBay: 8,
    levelsDefault: 4,
    load: { perLevelKg: 400, maxLoadPerBeamPairKg: 800, maxSinglePalletKg: 0 },
    aisle: { widthMmMin: 2400, widthMmDefault: 2800, crossAisleMm: 3200 },
    flueSpace: { transverseMm: 50, longitudinalMm: 100 },
    bottomBeamClearanceMm: 100,
    beamThicknessMm: 50,
    minPresentationPallets: 0,
    honeycombing: { verticalFactor: 0.92, horizontalDefault: 0.88 },
    fillFactor: 0.85,
    slotVolumeM3: 0.4,
    slotTypeCompat: ['Shelf'],
    storageType: 'tyre_rack',
    densityRating: 'medium',
    seismic: { designCategory: 'C', soilClassRating: 'B', importanceLevel: 2, anchorageRequired: true, bracingPattern: '2-bay' },
    structuralBayBlock: 1,
    rackMassKgPerPosition: 6,
    costPerPalletPositionUsd: 35,
  },
  {
    system_id: 'pallet_shuttle_single',
    name: 'Pallet Shuttle (single-deep)',
    category: 'pallet_shuttle',
    supplier_refs: ['Mecalux Pallet Shuttle', 'AR Racking Shuttle', 'HAI Radio Shuttle', 'Jungheinrich Shuttle'],
    bay: { widthMm: 2700, depthMm: 1200, heightMmDefault: 10000, heightMmRange: [6000, 14000] },
    slotsPerBay: 2,
    levelsDefault: 6,
    load: { perLevelKg: 2200, maxLoadPerBeamPairKg: 3000, maxSinglePalletKg: 1500 },
    aisle: { widthMmMin: 3200, widthMmDefault: 3500, crossAisleMm: 4000 },
    flueSpace: { transverseMm: 100, longitudinalMm: 200 },
    bottomBeamClearanceMm: 400,
    beamThicknessMm: 120,
    minPresentationPallets: 1,
    honeycombing: { verticalFactor: 0.95, horizontalDefault: 0.85 },
    fillFactor: 0.90,
    slotVolumeM3: 1.44,
    slotTypeCompat: ['PFP'],
    storageType: 'shuttle',
    densityRating: 'very_high',
    seismic: { designCategory: 'D', soilClassRating: 'C', importanceLevel: 2, anchorageRequired: true, bracingPattern: '2-bay' },
    structuralBayBlock: 2,
    rackMassKgPerPosition: 55,
    costPerPalletPositionUsd: 200,
    notes: 'Semi-automatic. Radio shuttle interoperable across vendors.',
  },
  {
    system_id: 'pallet_shuttle_mother_child',
    name: 'Pallet Shuttle (Mother-Child)',
    category: 'pallet_shuttle',
    supplier_refs: ['Mecalux', 'HAI Radio Shuttle'],
    bay: { widthMm: 2700, depthMm: 1200, heightMmDefault: 10000, heightMmRange: [6000, 14000] },
    slotsPerBay: 2,
    levelsDefault: 6,
    load: { perLevelKg: 2200, maxLoadPerBeamPairKg: 3000, maxSinglePalletKg: 1500 },
    aisle: { widthMmMin: 3200, widthMmDefault: 3500, crossAisleMm: 4000 },
    flueSpace: { transverseMm: 100, longitudinalMm: 200 },
    bottomBeamClearanceMm: 400,
    beamThicknessMm: 120,
    minPresentationPallets: 1,
    honeycombing: { verticalFactor: 0.95, horizontalDefault: 0.80 },
    fillFactor: 0.90,
    slotVolumeM3: 1.44,
    slotTypeCompat: ['PFP'],
    storageType: 'shuttle_mother_child',
    densityRating: 'very_high',
    seismic: { designCategory: 'D', soilClassRating: 'C', importanceLevel: 2, anchorageRequired: true, bracingPattern: '2-bay' },
    structuralBayBlock: 2,
    rackMassKgPerPosition: 55,
    costPerPalletPositionUsd: 260,
    notes: 'Fully automated orbital layout. Highest pallet density.',
  },
  {
    system_id: 'mini_load_asrs',
    name: 'Mini-Load ASRS (totes)',
    category: 'mini_load',
    supplier_refs: ['Dematic', 'SSI Schaefer', 'Vanderlande', 'Geek+'],
    bay: { widthMm: 800, depthMm: 600, heightMmDefault: 15000, heightMmRange: [10000, 24000] },
    slotsPerBay: 20,
    levelsDefault: 20,
    load: { perLevelKg: 50, maxLoadPerBeamPairKg: 100, maxSinglePalletKg: 0 },
    aisle: { widthMmMin: 1100, widthMmDefault: 1100, crossAisleMm: 2500 },
    flueSpace: { transverseMm: 30, longitudinalMm: 30 },
    bottomBeamClearanceMm: 200,
    beamThicknessMm: 50,
    minPresentationPallets: 0,
    honeycombing: { verticalFactor: 0.98, horizontalDefault: 0.90 },
    fillFactor: 0.92,
    slotVolumeM3: 0.12,
    slotTypeCompat: ['Auto'],
    storageType: 'asrs_mini_load',
    densityRating: 'very_high',
    seismic: { designCategory: 'D', soilClassRating: 'C', importanceLevel: 2, anchorageRequired: true, bracingPattern: 'full' },
    structuralBayBlock: 1,
    rackMassKgPerPosition: 2,
    costPerPalletPositionUsd: 350,
  },
];
