// Shared test fixtures for the engine. Keeps the test files focused on
// behaviour assertions instead of input boilerplate.

import type {
  EngineSku,
  EngineOpsProfile,
  EnginePallet,
  EngineRackSystem,
  EngineBuildingEnvelope,
  EngineMheClass,
  EngineProductivityCell,
  EngineRegionalContext,
} from '../../src/engine/models';

export const OPS: EngineOpsProfile = {
  operatingDaysPerYear: 300,
  productivityFactor: 0.82,
  productiveHoursPerDay: 18.67,
  shiftsPerDay: 2,
  hoursPerShift: 10,
  peakUplift: 1.35,
  sigmaStorage: 1.0,
  percentileDocks: 0.95,
  percentileStaging: 0.95,
  absenteeismPct: 0.08,
  leaveFraction: 0.12,
  sickReliefPct: 0.05,
  horizontalHoneycombingFactor: 0.88,
  gridEfficiencyThreshold: 0.88,
  preferredAspectRatio: 1.6,
  skuPeakCorrelationCoefficient: 0.3,
  floorloadPalletisationYield: 0.88,
  dsohDays: 14,
  forwardFaceDsohDays: { A: 1.0, B: 2.5, C: 0, D: 0 },
  dsohChangeByVelocity: { A: 0, B: 0, C: 0, D: 0 },
  paretoBreakpoints: { A: 0.2, B: 0.5, C: 0.8, D: 1.0 },
  replenTriggerDays: 0.5,
  clsLaneFillFactor: 0.9,
  crossAisleSpacingM: 22,
  crossAisleWidthM: 2.4,
  canopyAllowancePct: 0.11,
  canopyType: 'cantilever',
  canopyOverhangM: 1.2,
  canopyCoverageExemptMaxM: 1.2,
  maxSiteCoverage: 0.55,
  phase2HorizontalPct: 0.2,
  phase2VerticalPct: 0.1,
  softSpacePct: 0.2,
  clearHeightMm: 12500,
  ordersPerBatch: 5,
  repackSecPerPallet: 90,
  repackSecPerUnit: 2,
  adminFte: 5,
  supervisorFte: 4,
  totalStaff: 85,
  vasBenches: 4,
  returnsRatePct: 2,
  returnsHandleTimeHours: 0.3,
  qcSampleRate: 0.1,
  qcDwellHours: 8,
  avgDgSkuFootprintM2: 0.5,
  dgMultiplier: 2.5,
  packerThroughput: 60,
  amenitiesArea: 80,
  trainingAreaM2: 40,
  firstAidAreaM2: 15,
  palletFootprintM2: 1.21,
};

export const PALLETS: EnginePallet[] = [
  { pallet_id: 'T11', dimensionsMm: { length: 1100, width: 1100, height: 150 }, maxLoadKg: 1000 },
];

export const RACK: EngineRackSystem = {
  system_id: 'selective_t11',
  bay: { widthMm: 2400, depthMm: 1100, heightMmDefault: 9000 },
  slotsPerBay: 2,
  levelsDefault: 5,
  load: { perLevelKg: 2000, maxLoadPerBeamPairKg: 3000, maxSinglePalletKg: 1500 },
  aisle: { widthMmMin: 2800, widthMmDefault: 3000, crossAisleMm: 3500 },
  flueSpace: { transverseMm: 150, longitudinalMm: 300 },
  bottomBeamClearanceMm: 150,
  beamThicknessMm: 100,
  honeycombing: { verticalFactor: 0.92, horizontalDefault: 0.88 },
  fillFactor: 0.95,
  slotTypeCompat: ['PFP'],
  densityRating: 'low',
  structuralBayBlock: 3,
  rackMassKgPerPosition: 45,
};

export const ENVELOPE: EngineBuildingEnvelope = {
  clearHeights: { usableRackM: 11, sprinklerClearanceM: 1 },
  floor: { slabLoadingTPerM2: 5, totalFloorAreaM2: 10000 },
  seismic: { designCategory: 'C', allowableRatio: 0.8 },
  columnGrid: { spacingXM: 12, spacingYM: 24 },
  coldChain: {
    ambientZoneM2: 8000,
    chilledZoneM2: 600,
    frozenZoneM2: 200,
    antechamberRequired: false,
    antechamberM2: 0,
  },
  customsBonded: { required: false, holdAreaPct: 0.03, fencedCageM2: 0 },
  mezzanine: { available: true, tiers: 2, perTierMaxM2: [1200, 900] },
  power: { backupGeneratorKva: 500, gridReliabilityHoursPerDay: 24 },
};

export const PRODUCTIVITY: EngineProductivityCell[] = [
  {
    method: 'reach_truck',
    unitType: 'pallet',
    slotType: 'PFP',
    staticTimeSecPerUnit: 45,
    travelModelType: 'sqrt_area',
    travelCoefficient: 1.0,
    baselineZoneAreaM2: 2500,
    derivedRateAtBaseline: 28,
  },
  {
    method: 'voice',
    unitType: 'case',
    slotType: 'PFP',
    staticTimeSecPerUnit: 15,
    travelModelType: 'sqrt_area',
    travelCoefficient: 1.2,
    baselineZoneAreaM2: 2000,
    derivedRateAtBaseline: 180,
  },
  {
    method: 'rf_scan',
    unitType: 'case',
    slotType: 'PFP',
    staticTimeSecPerUnit: 22,
    travelModelType: 'sqrt_area',
    travelCoefficient: 1.2,
    baselineZoneAreaM2: 2000,
    derivedRateAtBaseline: 140,
  },
  {
    method: 'rf_scan',
    unitType: 'each',
    slotType: 'Shelf',
    staticTimeSecPerUnit: 18,
    travelModelType: 'sqrt_area',
    travelCoefficient: 1.1,
    baselineZoneAreaM2: 1500,
    derivedRateAtBaseline: 80,
  },
  {
    method: 'pick_to_light',
    unitType: 'each',
    slotType: 'CLS',
    staticTimeSecPerUnit: 6,
    travelModelType: 'sqrt_area',
    travelCoefficient: 0.8,
    baselineZoneAreaM2: 800,
    derivedRateAtBaseline: 360,
  },
  {
    method: 'vna',
    unitType: 'pallet',
    slotType: 'PFP',
    staticTimeSecPerUnit: 35,
    travelModelType: 'sequential_hv',
    travelCoefficient: 1.0,
    baselineZoneAreaM2: 3000,
    derivedRateAtBaseline: 24,
    vnaLiftSpeedMpm: 30,
  },
  {
    method: 'decant',
    unitType: 'pallet',
    slotType: 'PFP',
    staticTimeSecPerUnit: 300,
    travelModelType: 'zero',
    travelCoefficient: 0,
    baselineZoneAreaM2: 0,
    derivedRateAtBaseline: 12,
  },
  {
    method: 'vas',
    unitType: 'each',
    slotType: 'Shelf',
    staticTimeSecPerUnit: 45,
    travelModelType: 'zero',
    travelCoefficient: 0,
    baselineZoneAreaM2: 0,
    derivedRateAtBaseline: 80,
  },
];

export const MHE: EngineMheClass[] = [
  {
    mhe_id: 'walkie_pallet',
    category: 'walkie',
    travelSpeedKph: 5,
    liftSpeedMpm: 5,
    liftHeightMmMax: 200,
    battery: { type: 'lithium_opportunity', chargingFootprintM2PerUnit: 1, swapStationM2: 0, chargingKva: 2 },
    utilisationTargetDefault: 0.55,
  },
  {
    mhe_id: 'reach_truck_single',
    category: 'reach',
    travelSpeedKph: 12,
    liftSpeedMpm: 40,
    liftHeightMmMax: 11000,
    battery: { type: 'lithium_opportunity', chargingFootprintM2PerUnit: 3, swapStationM2: 0, chargingKva: 10 },
    utilisationTargetDefault: 0.72,
  },
  {
    mhe_id: 'vna_turret',
    category: 'very_narrow_aisle',
    travelSpeedKph: 10,
    liftSpeedMpm: 30,
    liftHeightMmMax: 14000,
    battery: { type: 'lithium_opportunity', chargingFootprintM2PerUnit: 2, swapStationM2: 0, chargingKva: 5 },
    utilisationTargetDefault: 0.7,
    ratePerTaskPerHour: { putawayPallet: 28, replenPallet: 24, retrievePallet: 28 },
  },
  {
    mhe_id: 'llop',
    category: 'order_picker',
    travelSpeedKph: 12,
    liftSpeedMpm: 0,
    liftHeightMmMax: 300,
    battery: { type: 'lithium_opportunity', chargingFootprintM2PerUnit: 1.5, swapStationM2: 0, chargingKva: 3 },
    utilisationTargetDefault: 0.7,
  },
];

export const REGIONAL: EngineRegionalContext = {
  regionId: 'KR',
  officeM2PerFte: 9,
  surauRequired: false,
  muslimWorkforcePct: 0,
  ramadanDerate: { active: false, factor: 1, days: 0 },
  backupGeneratorMandatory: false,
};

export const REGIONAL_MY: EngineRegionalContext = {
  regionId: 'MY',
  officeM2PerFte: 10,
  surauRequired: true,
  muslimWorkforcePct: 0.7,
  ramadanDerate: { active: true, factor: 0.82, days: 30 },
  backupGeneratorMandatory: false,
};

export function mkSku(id: string, weeklyMean: number, overrides: Partial<EngineSku> = {}): EngineSku {
  const w = new Float32Array(52).fill(weeklyMean);
  return {
    id,
    category: 'FMCG',
    weeklyUnits: w,
    weeksOnFile: 52,
    unitCubeCm3: 5000,
    unitWeightKg: 0.5,
    caseQty: 24,
    inboundPalletId: 'T11',
    outboundPalletId: 'T11',
    palletTi: 4,
    palletHi: 5,
    stackable: true,
    tempClass: 'ambient',
    halalStatus: 'halal',
    channelMix: { retailB2bPct: 0.7, ecomDtcPct: 0.2, marketplacePct: 0.1 },
    ...overrides,
  };
}
